### ISSUE TITLE
可否添加一个新的参数description (add a @description parameter?)

### ISSUE THREAD

**Issue by just-for-krystal** [zxj5470/BugKotlinDocument#12]
用来描述函数的工作，显示就和其他参数一样@Description，在它下面额外多空一行，以进行区分

**Comment by zxj5470** [comment]
@description 好像不是官方标准 https://kotlinlang.org/docs/reference/kotlin-doc.html 的内容，所以就不添加了…… 

(那啥 issue 尽量还是用英文吧……) 

-------
@description doesn't seem to be part of the official standard document https://kotlinlang.org/docs/reference/kotlin-doc.html, so it won't be added.
