### ISSUE TITLE
for annotated parameters double quotes and bracket appears ..

### ISSUE THREAD

**Issue by monsterbrain** [zxj5470/BugKotlinDocument#13]
![image](https://user-images.githubusercontent.com/10105094/59403786-cb44d080-8dc1-11e9-8a26-e32f189b7bd2.png)

for the annotated parameters (except last one) double quotes and bracket is showing ....

**Comment by zxj5470** [comment]
# Fix it.
You can download a nightly-build when the update is pending JetBrains'approval.
https://ci.appveyor.com/project/zxj5470/bugkotlindocument/build/artifacts/

**Comment by monsterbrain** [comment]
Nice. Thanks a lot.
