### ISSUE TITLE
生成注释的2个bug及方案建议

### ISSUE THREAD

**Issue by yizeliang** [zxj5470/BugKotlinDocument#2]
https://github.com/zxj5470/BugKotlinDocument/blob/edfedff963d830f43a5582fee953a3bfbdeb2a89/src/main/kotlin/cn/wjdghd/MainComponent.kt#L95

建议改成

`sb.append(it.trim())`

因为参数可能换行了,会多出一个`\n`来

https://github.com/zxj5470/BugKotlinDocument/blob/edfedff963d830f43a5582fee953a3bfbdeb2a89/src/main/kotlin/cn/wjdghd/MainComponent.kt#L102

建议替换为
`rturn realNext.replaceFirst(thisLine, sb.toString()) `

目前在生成 kotlin 类注释的时候有发现,会把第一个函数的 `/**`也给替换掉

**Comment by zxj5470** [comment]
改用document.insertString……当年脑抽了

**Comment by zxj5470** [comment]
完完全全修复……欢迎体验新版。

**Comment by yizeliang** [comment]
ok
.3q ,有兴趣上传到插件市场么

**Comment by zxj5470** [comment]
一直都在插件市场里面啊……
